import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthModalProvider from "@/context/AuthModalContext";
import AuthModal from "@/components/Modal/AuthModal";
import { ImageContextProvider } from "@/context/ImageModalContext";
import Footer from "@/components/Footer";
import { CartContextProvider } from "@/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthModalProvider>
          <ImageContextProvider>
            <CartContextProvider>
              <AuthModal />
              <div className="flex flex-col min-h-[100vh]">
                {children}
                <Footer />
              </div>
            </CartContextProvider>
          </ImageContextProvider>
        </AuthModalProvider>
      </body>
    </html>
  );
}
