import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AuthModalProvider from "@/context/AuthModalContext";
import AuthModal from "@/components/Modal/AuthModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthModalProvider>
          <Header />
          <AuthModal />
          <div className="m-and-t:[margin-top:calc(var(--header-mobile-height)_+_var(--products-mobile-sort-bar))] w-full overflow-hidden">
            <main className="bg-primaryBgColor py-8 w-full">{children}</main>
          </div>
        </AuthModalProvider>
      </body>
    </html>
  );
}
